### ISSUE TITLE
Drop item config not working (1.19.2)

### ISSUE THREAD

**Issue by Skipperino** [B1n-ry/Youre-in-grave-danger#108] opened 2023-03-25 15:26 UTC
As described in the title, item loss configuration simply does not work. At least on a dedicated hosting server. Config for item loss has been set to 'true' with the percent of loss at '100' and amount of items to be destroyed is set to a range of 1-10.  However, after a player retrieves their gravestone, no items are lost.

This occurrence is being recorded from a hosting service on Bisect hosting. It is worth noting that other configs have also been shotty on this hosting service, where sometimes the config will simply not work at all vs in singleplayer where it works just fine.

OS is Windows 10 with MC version java 1.19.2

![Screenshot 2023-03-22 163616](https://user-images.githubusercontent.com/101917712/227726567-48ebf1c0-32b6-441e-b23a-6393cb0fbb14.jpg)

**Comment by B1n-ry** [comment] 2023-03-25 15:41
So it works like intended in a singleplayer world? You are using the configs in the server files, and not the client screen thing correct? Have you restarted the server after the config change? There might also be an issue if the config file has invalid syntax, and then it will load default configs. If that's what's happened the game should write `Loading default YIGD config due to an error reading the config file. Delete yigd.toml, and a new working config file should generate` in the log.
I would assume you've looked on all of these things, but I really don't know what's happened if it works on your singleplayer world, but not on the server. The code should be the exact same on dedicated server as well as a singleplayer world. And it's packaged with the generation of the graves, so if one would fail I'd expect both to do so.
I've not yet taken a look on this due to a problem I'm having with my development environment, but I will as soon as I figure it out, or the issue is resolved somehow in any other way.
I assume you're the one who made a comment on the curseforge page too. Sorry I haven't checked on it or done anything, but as I said, I'm having troubles doing so

**Comment by Skipperino** [comment] 2023-03-27 20:44
Currently, I wouldn't assume that it's defaulting to the original config as some of the settings that I have put in the config work seamlessly. Such setting the chance of a zombie spawning on gravestone retrieval.

**Comment by B1n-ry** [comment] 2023-03-28 20:09
Found the issue. I think I somehow made it possible remove items when items were not supposed to be able to be removed, and then items that should've been able to be removed wasn't able to be removed. I'll reopen the issue since a fix is not out to the public yet, but will close the issue as soon as that happens. Thanks for reporting in! I'll make sure all maintained versions are updated, and then I'll release the updates. Hopefully won't take too long

**Comment by Skipperino** [comment] 2023-03-31 02:24
> Found the issue. I think I somehow made it possible remove items when items were not supposed to be able to be removed, and then items that should've been able to be removed wasn't able to be removed. I'll reopen the issue since a fix is not out to the public yet, but will close the issue as soon as that happens. Thanks for reporting in! I'll make sure all maintained versions are updated, and then I'll release the updates. Hopefully won't take too long

Absolutely! and thank you so much for your help and commitment man. Same can't be said for some of the other mod makers that have glaring issues with their mods. Keep it up man.

**Comment by Skipperino** [comment] 2023-03-31 02:25
Didn't mean to close. But thank you for all your work man. Keep it up!

**Comment by B1n-ry** [comment] 2023-04-23 18:53
So slightly later than I'd hoped, I've released a new version fixing this. Thanks for reporting it, again. Sorry for taking longer than expected

**Closed as completed by B1n-ry** 2023-04-23 18:53 UTC
