### ISSUE TITLE
Don't get Traveller's backpack back from trinket slot

### ISSUE THREAD

**Issue by oldjollysanta** [B1n-ry/Youre-in-grave-danger#84] opened 2022-11-05 10:56 UTC
**Describe the bug**
When putting a Traveller's backpack in the trinket slot and dying, it's completely lost when collection your grave.

**To Reproduce**
1. In Traveller's backpack config, set trinketsIntegration to true (all other settings default)
2. Put backpack in trinket slot
3. /kill
4. Collect grave
5. Backpack missing from trinket slot (completely removed from inventory)

**Expected behavior**
Backpack to be where it was before death.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19.2
 - Version: 1.4.5

**Additional context**
Tested with trinketsIntegration  disabled and backpack equipped, functions correctly.

**Comment by B1n-ry** [comment] 2022-11-06 13:51
Seems to be the equipBackpack method from travelers backpack equipping in the wrong slot, but I could try to have the implementation disabled if the travellers backpack trinket integration config is enabled. 
Thanks for the report. I can't check this out atm, but I'll let you know once I release a version with a fix for this

**Comment by oldjollysanta** [comment] 2022-11-07 04:34
No problem at all, I understand you have other stuff to do and I appreciate the reply. I'll check back every now and then for an update

**Comment by B1n-ry** [comment] 2022-11-27 20:22
I've now updated the mod, including this fix. When the trinket integration config in travelers backpack is enabled the travelers backpack module should just not load at all, which should fix the issue. Let me know if you would find anything wrong that my testing didn't
Anyway thanks for reporting this!

**Comment by paulwsully** [comment] 2023-01-08 01:59
This seems to still be an issue. Exact same repro steps as the original issue report. Confirmed `"trinketsIntegration": true` is set in travelersbackpack.json.

**Comment by B1n-ry** [comment] 2023-01-08 10:46
Hmm weird... I really thought I fixed and tested this. Trevelers backpack recently updated with "Fixed You're in Grave Danger Compatibility issue - backpack is being stored in grave now". Could be something there that broke. Not sure exacly what was wrong before (I didn't get any reports of this), and I'm not sure what changed in the travelers backpack code in this fix, but I'll look into it.

**Comment by paulwsully** [comment] 2023-01-09 16:30
I appreciate ya taking a look! As a fellow developer, I totally understand that feeling 😅

To be a bit more clear, I am also using the latest version of the mod, as well as latest Fabric version, if that helps!

**Comment by B1n-ry** [comment] 2023-01-15 17:11
Ok this time it's actually fixed. Travelers backpack tell trinkets that all the backpacks should be deleted on death (if it could be placed), and I think that's why it didn't save. Because I asked trinkets what would happen with each item too. I've updated the mod now anyway, and the issue is now properly fixed, **with testing**

**Closed as completed by B1n-ry** 2023-01-15 17:11 UTC
