### ISSUE TITLE
Items from the origins power type "type": "origins:keep_inventory", do not keep upon death

### ISSUE THREAD

**Issue by Fintris** [B1n-ry/Youre-in-grave-danger#86] opened 2022-11-21 06:16 UTC
I'm assuming this is due to the gravestone just storing everything in your inventory and not checking if its supposed to be there or not. This could probably affect other mods with items that you don't drop on death.

**Comment by B1n-ry** [comment] 2022-11-21 06:38
I actually provided compatibility with origins quite recently, and check if items would drop or stay in inventories, but I assume I didn't check weather or not the entire inventory should be kept or not. I'll look into it, and let you know how it goes

**Comment by Fintris** [comment] 2022-11-21 08:00
Cool, im actually using a power that keeps the inventory of an item with specific nbt and it works on fabric 1.19.2 without YIGD but not on fabric 1.19.2 with YIGD

**Comment by B1n-ry** [comment] 2022-11-23 19:46
Actually I can't quite find what I've done wrong. Could you please provide more information? Like if this origin power (inventory) is from an extra mod or if you've made the origin power with a datapack, and what it looks like?
Basically all the info I could need to reproduce this myself

**Comment by B1n-ry** [comment] 2022-11-27 20:25
I *think* I might've solved the issue. I feel like the information was kinda unclear in some regards, but I've done something which I think should do what you want. If I did anything wrong feel free to reopen the issue, but I'll close it since I've updated the mod and included what I think you were asking for.
Thank you for reporting this!

**Closed as completed by B1n-ry** 2022-11-27 20:25 UTC
