### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by WYL23456** [B1n-ry/Youre-in-grave-danger#58] opened 2022-06-19 17:51 UTC
[error.2022-6-19_23.20.22.zip](https://github.com/B1n-ry/Youre-in-grave-danger/files/8936078/error.2022-6-19_23.20.22.zip
**To Reproduce**
Steps to reproduce the behavior:An error occurred with sodium 
1. An unknown death
2. Client crash 
3.report errors 

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.16.5 fabric 
 - Version: 1.0.9

**Comment by B1n-ry** [comment] 2022-06-19 17:58
Seems to be an issue with sodium and the glowing grave feature for 1.16. You can fix this temporarily by going in to your configs, and change the config `glowingGrave` to `false`. I'll see when I can get out the next 1.16 version but I will definitely have it fixed in that version

**Comment by WYL23456** [comment] 2022-06-19 18:02
OK，I'll try
thank you

**Comment by B1n-ry** [comment] 2022-06-19 21:54
Actually when looking over this to fix it, I didn't encounter this issue even with sodium installed. I think there could be some other mod perhaps that's causing this. If you are playing a publicly available modpack, you can send me a link, and if you are not, I would appreciate if you could send your modpack zip (exported modpack profile). If you don't want to that's fine. Just tell me if you decide not to help. Getting that zip would save a lot of time that I don't really bother spending, unless I know you won't send the zip

**Comment by WYL23456** [comment] 2022-06-19 22:50
ok,This file is so big that I can't send mod. Please give me your email.

**Comment by WYL23456** [comment] 2022-06-19 22:52
Or discord

**Comment by B1n-ry** [comment] 2022-06-19 23:43
I've messaged you on discord, assuming you are the wyl who joined my discord server

**Comment by B1n-ry** [comment] 2022-06-20 11:08
Ok I managed to find which mod that caused this, as well as a permanent fix that doesn't even require me to update the mod. So the mod causing the issue is called `BlockMeterFabric`. I found that using a slightly older version the issue disappears. You can download the other version from [here](https://www.curseforge.com/minecraft/mc-mods/blockmeterfabric/files/3056478)

Let me know if you find anything else that seems off or any other bugs/crashes

**Closed as completed by B1n-ry** 2022-06-20 11:08 UTC
