### ISSUE TITLE
Grave destroyed by Twilightforest hydra

### ISSUE THREAD

**Issue by jonalange** [B1n-ry/Youre-in-grave-danger#89] opened 2022-12-04 23:06 UTC
A friend and myself were running around in the twilight forest and tried to fight the hydra. He got to close, she did a big attack, he was onehit and for some reason the grave either didn't spawn at all or it got destroyed by the hyrda.

Is there any way to get back the items via command? Are the items stored somewhere in a file to get them back?

**Comment by B1n-ry** [comment] 2022-12-05 05:55
Which version of the mod are you using? This sounds like an issue I've fixed. 
To restore a grave, try `/yigd restore [user]` or `/yigd moderate` (and navigate to the grave you want to restore)

**Comment by jonalange** [comment] 2022-12-05 14:40
Sorry for not providing that.
We are using YIGD fabric 1.4.6 with fabric version 0.14.10 and twilight forest 4.2.310

Mc 1.19.2

**Comment by jonalange** [comment] 2022-12-05 14:55
Just an idea we got right now: Could this be a problem in combination with charm of keeping from twilightorest? We will test that later

**Comment by B1n-ry** [comment] 2022-12-05 15:43
Yeah charm of keeping is known to delete items it's supposed to keep. However I don't think it's an incompatibility due to me being able to reproduce it without yigd present

**Comment by jonalange** [comment] 2022-12-05 17:27
Well, that could be true, but the grave didn't even spawn or the hydra destroyed it. It was a bit too hectic to notice it.

**Comment by B1n-ry** [comment] 2022-12-05 17:47
You can use the command `/yigd moderate` and select a player, or use the command `/yigd grave [user]`, then try and find the grave. Filter by destroyed, and if it's destroyed you should be able to find and destroy it there. If it's not there I'm sorry, but there's not really anything I can do

**Comment by B1n-ry** [comment] 2023-01-15 17:13
I'll close this issue as there's a chance that this wasn't an error from my side, and twilight has fixed the charm of keeping issue. Let me know if this would happen again however, and I will take a look at it again. Thanks for reporting it though!

**Closed as completed by B1n-ry** 2023-01-15 17:13 UTC
