### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by HelIwalker** [B1n-ry/Youre-in-grave-danger#93] opened 2022-12-31 11:43 UTC
1.18.2 fabric, I am the owner (administrator) of the server, I stole his tomb after my friend died (/yigd rob XXXXX), his tomb has been taken back, but I can still steal him all the time Tombs to grow my experience.

**Comment by B1n-ry** [comment] 2022-12-31 13:25
Yes the command is supposed to be a sort of "failsafe" if something would go wrong and items would otherwise be lost. You can still rob/restore graves with commands, since some bug might have happened that told the game the grave was looted even though it wasn't. All of the known bugs of this I've fixed, but if for some reason there would be a new issue I still want players to not lose all their items they had when they died.

This is not a bug, it's a feature. Thanks for reporting in though! I'll close this issue since I have no intention of changing this behaviour, but feel free to let me know if you experience anything else that could potentially be an issue. I rather have too many issues than just a few, since then I might actually be aware of all actual bugs

**Closed as completed by B1n-ry** 2022-12-31 13:25 UTC
