### ISSUE TITLE
Glowing shader not rendered

### ISSUE THREAD

**Issue by ekubocult** [B1n-ry/Youre-in-grave-danger#27] opened 2022-02-09 22:19 UTC
Hi there,

Ive ran into an issue when using this mod on my server. The grave generates perfectly and gives you your items back, however it doesnt show the coordinates to the grave, instead giving an error message.

To reproduce the error we all tried dying on the server, and as i said the grave generates normally but the coordinates dont show up.

Desktop
 - OS: windows
 - Minecraft Version: 1.18.1
 - Version: 1.0.6

this is what pops up in chat instead of the grave coordinates:
![image](https://user-images.githubusercontent.com/99367982/153299833-0f98754a-a7ac-4e7e-91fb-ae6f6225f7a6.png)

any help would be greatly appreciated, thanks so much

**Comment by B1n-ry** [comment] 2022-02-09 22:23
Are you using 1.18 or 1.16? Mod version 1.0.6 is for 1.16, but you have said you ised 1.18.1... 
Also are any other texts not decoded too? If you try to use `/yigd grave`, will the texts display in a similar way?

Can I also see that error message you are getting?

**Comment by ekubocult** [comment] 2022-02-09 23:20
> 

Hi, my mistake, I had downloaded the wrong version of the mod. The error message I was getting was the screenshot of the text I posted. 
Now the version of the mod I have is the same as the version of minecraft I use, the coordinates now show up and work normally. Although now I have another issue, where the gravestones are appearing white. I dont use any textures or shaders, do you know what might cause this?

**Comment by B1n-ry** [comment] 2022-02-09 23:28
I assume that you are playing version 1.2.16 of the mod now, yes?
Anyway I have a setting causing graves to be able to have a glowing effect. Since vanilla only has methods in place to render entities this way, I've tried to implement myself that this shader is drawn if a grave is rendered. I guess that the code went bad somehow. I know this bug was existing in earlier versions as I had not figured out how this would be done. If it is not solved by restarting the game or spawning a new grave, please send me what mods you're using (preferably if you're using a public modpack, the modpack name), and in the meantime disable the glowing effect in the config file (or in modmenu config screen)
graveSettings -> graveRender -> glowing, or something like that

**Comment by ekubocult** [comment] 2022-02-10 17:48
hi, im sorry for the delayed response. how do i access the config file for this mod? i use apex hosting and cant seem to find it

**Comment by B1n-ry** [comment] 2022-02-10 19:40
Resolved in newest update (for 1.18.1 it's mod version 1.2.17)

**Closed as completed by B1n-ry** 2022-02-10 19:40 UTC

**Comment by ekubocult** [comment] 2022-02-10 20:23
thank you so much!

**Comment by B1n-ry** [comment] 2022-02-10 20:23
Also sorry I somehow missed your question (I hope you will still see this even if the issue is closed). You can find the config file in the config folder. It's called `yigd.toml`. The config in this case is changed on the client however, as it handles the rendering
