### ISSUE TITLE
Compatibility with Utility Belt

### ISSUE THREAD

**Issue by Abbie5** [B1n-ry/Youre-in-grave-danger#146] opened 2024-01-29 18:52 UTC
Currently, items in your utility belt get deleted when you die if YIGD is installed. 

https://modrinth.com/mod/utility-belt

Log: https://0x0.st/HDqf.txt

**Comment by B1n-ry** [comment] 2024-01-29 21:52
Thank you for reporting! I believe I've found the cause of this issue. The utility belt will when the player inventory is cleared, clear the belt itself. When YiGD stores a player's inventory in a grave, the player inventory is cleared afterwards as no items should drop by mistake, duplicating it. This clears the already stored utility belt.
I've fixed it on my side, and will release a new version hopefully within a few days

**Comment by B1n-ry** [comment] 2024-02-08 20:39
Compat is fixed in yigd 2.0.0-beta-8. Thank you for reporting in the issue! Let me know if you would experience any other problem with this mod!

**Closed as completed by B1n-ry** 2024-02-08 20:39 UTC
