### ISSUE TITLE
Incompatible with Accessories Slots (Items disappearing)

### ISSUE THREAD

**Issue by BlazingTwist** [B1n-ry/Youre-in-grave-danger#186] opened 2024-10-26 11:30 UTC
I thought this was related to #183, however this appears to be a separate issue.

#### Minimum required mods:
- [Accessories 1.1.0-beta.15](https://modrinth.com/mod/accessories/version/5CkHnpcM)
- [yigd 2.4.11](https://modrinth.com/mod/yigd/version/2.4.11)
- [owo-lib 0.12.15](https://modrinth.com/mod/owo-lib/version/0.12.15+1.21)
- [fabric-api 0.106.0](https://modrinth.com/mod/fabric-api/version/0.106.0+1.21.1)
- [cloth-config 15.0.140](https://modrinth.com/mod/cloth-config/version/15.0.140+fabric)

#### Steps to rerpoduce:
Equip an item in one of the extra slots, like this:
![image](https://github.com/user-attachments/assets/4d30144d-4180-4973-8bbb-2a89a3af4339)

Die from Fall Damage.
Pick up the grave.
The item is not visible (when using e.g. the Elytra-Slot mod, the Elytra cannot be used anymore)
![image](https://github.com/user-attachments/assets/3e3af02c-5c29-4cfc-91ed-5f28c4f61621)

After opening the Accessories hud, the item **appears** to be equipped. (Same as first image)
However, after saving/quitting and reopening the world, the item disappears.

---

It seems picking up graves equips accessories to the "wrong" slot?

There is no additional info in the logs:
```
[13:31:27] [Server thread/INFO]: BlazingTwist fell from a high place
[13:31:27] [Render thread/INFO]: [System] [CHAT] BlazingTwist fell from a high place
[13:31:28] [Render thread/INFO]: [System] [CHAT] Your grave is located at X: 2 / Y: 69 / Z: 20 / minecraft:overworld
[13:31:44] [Server thread/INFO]: BlazingTwist claimed a grave belonging to BlazingTwist at 2, 69, 20, minecraft:overworld
```

**Comment by B1n-ry** [comment] 2024-11-01 13:00
Seems to be fixed in accessories 1.1.0-beta.16.
I could reproduce the issue on accessories beta.15-version, but on beta.16 it disappeared. Thank you for reporting the issues anyway!

**Closed as completed by B1n-ry** 2024-11-01 13:00 UTC
