### ISSUE TITLE
Graves float when playing with Hardcore Revival Mod

### ISSUE THREAD

**Issue by G1tCub3** [B1n-ry/Youre-in-grave-danger#90] opened 2022-12-09 09:23 UTC
**Describe the bug**
Since I installed the Hardcore Revival (Fabric Edition) mod by BlayTheNinth, when you die the grave is generated one block above your death and is therefore floating.

**To Reproduce**
1. Choose your favorite way to die.
2. Click on 'Accept your fate'.
3. You died.
4. Click on 'Respawn'.
5. Your grave is now floating.

**Expected behavior**
I was expecting the grave to be on the ground.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.19.2
 - Fabric loader 0.14.11
 - YIGD Version: 1.4.6
 - HR (FE) Version: 9.0.1

**Additional context**
No particular modpack, just a bunch of mods.
Playing on a server.
Before you die, Hardcore Revival Mod makes you "swim" on the ground until someone rescue you. When you die, the player will first stand-up and then die immediately after (almost at the same time?). I think that this is causing the issue.

Honestly it's not gamebreaking and the graves are meant to be retrieve anyway, so take your time.

**Screenshots**
Didn't take any but I can if you want to.

**Comment by B1n-ry** [comment] 2023-01-15 17:03
I could not reproduce the issue. I chose "falling to my death", and the grave generated on the ground. If you still have this problem, let me know exactly how you die. Thanks for reporting anyway!
I'll close the issue as completed since it does not happen for me. Feel free to reopen the issue

**Closed as completed by B1n-ry** 2023-01-15 17:03 UTC
