### ISSUE TITLE
Inventory duplication

### ISSUE THREAD

**Issue by th3heindnsiw** [B1n-ry/Youre-in-grave-danger#57] opened 2022-06-16 06:42 UTC
**Describe the bug**
The grave will be created if you die in Minecraft. But if you intentionally crash your game (before it autosaves), you will still have your loot while the grave is at the place you die, containing all the loot.

**To Reproduce**
Steps to reproduce the behavior: (on MacOS)
1. Die in Minecraft with some items in your inventory, but don't click 'Respawn' or 'Title Screen'.
2. Go to Activity Monitor and then find 'java'.
3. Force quit 'java'.
4. Re-join the world. You will see you still have your loot, but if your death location, you will see the grave

**Expected behavior**
When I forced quit Minecraft and then re-joined my world, I expected to have my loot while no grave spawned at my last death location.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Minecraft Version: 1.19
 - Version: 1.4.1-beta1

**Screenshots**
Not applicable

**Comment by B1n-ry** [comment] 2022-06-16 08:06
I would say that this is rather on mojang's side of things. I would expect you to, if you died, actually die. When a player with this mod on dies, all their items is copied onto the server, and then the player inventory is cleared. So I don't see a way (or reason for that matter) to fix this. I will only resolve any bugs/glitches/crashes and stuff that's caused by this mod. I hope you understand why this won't get fixed. 
If there however is a reason that you forcequit, like if the game hang and nothing worked, let me know and I will do my best to fix it. Other than that I will close this issue. You can reopen it or open a new one if you have any other problems

**Closed as not planned** 2022-06-16 08:06 UTC
